version: "3"
services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8080 # This will be overridden by Docker Compose's dynamic port binding
    volumes: # Mount your project files
      - maven_cache:/root/.m2
    expose:
      - 8080
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - spring-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  maven_cache: # Volume for Maven cache
