name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      continue-on-error: true
    # - name: Run the docker compose
    #   run: docker-compose up --build
    - name: dir command
      run : dir
