name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      continue-on-error: true
    
      
    - name: Remove old container
      run: docker rm -f my_container
      continue-on-error: true
      
    - name: Remove old image
      run: docker rmi my-app-spring:latest
      continue-on-error: true
      
    - name: Build Docker image
      run: docker build -t my-app-spring:latest .

    - name: Create and start new container
      run: docker run -d --name my_container -p 8080:8080 my-app-spring:latest
